name: Huis
favicon: null
layout_spectrum: 0.24847
typography_spectrum: 0.61721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d0b'
    - '#38404b'
    - '#fffffd'
    - '#e3b371'
    - '#ba783b'
  brandStrength: 0.25
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
