layout_spectrum: 0.9685445
typography_spectrum: 0.3234043
color:
  saturation: 0.7106383
  lightness: 0.6978723
  brandStrength: 1
  brandColors:
    - '#FBF7EC'
    - '#3D362E'
    - '#CED9EC'
    - '#797873'
    - '#ACA9A2'
  rhythmicContrast: 0.7723404
name: Huis
