layout_spectrum: 0.9685445
color:
  saturation: 0.5744681
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#FBF7EC'
    - '#3D362E'
    - '#CED9EC'
    - '#797873'
    - '#ACA9A2'
  rhythmicContrast: 1
typography_spectrum: 0.3234043
name: Huis
