purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#2D2319'
    - '#4E4534'
    - '#605748'
    - '#7D766C'
    - '#978D83'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
name: Huis
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.61721
layout_spectrum: 0.24847
